### ISSUE TITLE
Invalid method name is giving unexpected response

### ISSUE THREAD

**Issue by sonalnegivarma** [NHSDigital/spine-directory-service-api#79]
The SDS API supports GET method. When passing POST. It is providing unexpected response code.

Endpoint -  POST: https://int.api.service.nhs.uk/spine-directory/Endpoint
Query Parameter - org-code-  YGMYH and service-id: urn:nhs:names:services:pds:MCCI_IN010000UK13
Headers - apikey: myG6cYQthVUzGeA0sHqCVPp3aSSZItF3

Actual Response code - 502 - Bad Gateway
Expected Response code - 405 -Method not allowed

**Comment by michael-kainos** [comment]
Will fix this in the next release

**Comment by sonalVarma** [comment]
@michael-kainos , SDS api's are reachable and environment is up. I have tried to retest this defect but issue still persists.
![image](https://user-images.githubusercontent.com/75005842/100216952-e6b18600-2f38-11eb-8d49-51e5baab6f71.png)

Expected Response - 405 -Method not allowed

**Comment by michael-kainos** [comment]
@bartek-sarul is this fix in place or is this actual result correct?

**Comment by bartek-sarul** [comment]
This might be Apigee related then
I'll check tomorrow

**Comment by bartek-sarul** [comment]
@sonalVarma indeed that was Apigee related issue. Couple of issues were involved here:
1. Only query parameters were uses to build cache key. This made it use data from cache even if path or method was different 
2. 405 requires `Allow` header in response for Apigee to treat that as non-error response
3. Caching was done before apikey check so once you had data cached, subsequent requests didn't have to have apikey and were passing.
All of those are fixed in 
https://gpitbjss.atlassian.net/browse/NIAD-768 
https://github.com/NHSDigital/spine-directory-service-api/pull/109/files
but see that this PR base is another feature branch and not the master one.

I'll let you know when this is ready once the other branch is tested and merged in.

**Comment by bartek-sarul** [comment]
@sonalVarma @michael-kainos this is now ready in master branch and available at https://internal-dev.api.service.nhs.uk/spine-directory

**Comment by sonalnegivarma** [comment]
Thanks! @bartek-sarul Retesting is completed. No issues observed.
